In [1]:
import pandas as pd
import requests
import json
import os
import numpy as np
from tqdm import tqdm

In [2]:
file_list = os.listdir('preprocess_data/')

In [3]:
total_list = []
code_list = []
for code in tqdm(file_list):
    code_list.append(code)
    df_list = []
    for file_name in os.listdir('preprocess_data/{}'.format(code)):
        df_list.append(pd.read_csv('preprocess_data/{}/{}'.format(code,file_name)))
    df = pd.concat(df_list,axis=0)
    df = df.replace('--',np.nan)
    df = df.replace('</tr>',np.nan)
    df_names = df['报告日期']
    del df['报告日期']
    df.astype('float32')
    df['2019-09-30'] = df.apply(lambda x:x['2019-09-30'] if x['2019-09-30'] != np.nan  else np.mean(x),axis=1)
    df_new = df['2019-09-30'].values.T
    total_list.append(df_new)

  0%|          | 0/136 [00:00<?, ?it/s]/home/luoyingsong/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.


100%|██████████| 136/136 [00:09<00:00, 13.98it/s]

In [4]:
df['2019-09-30'].values.T

array(['-2.87', '8.29', '-2.86', '-5.46', '-5.58', '88.21', '-5.91',
       '-6.11', '-55.52', '-6.13', '-2.87', nan, '10.69', '21.05',
       '-148.09', '1.08', '0.94', '25.46', '2008.53', '53.23', nan,
       '46.77', nan, nan, '113.81', nan, nan, nan, '111.48', '94.96', nan,
       nan, -9.5, -327.71, -7.04, -1.79, '-0.55', nan, nan, '4511542',
       '373888', '-251570', '-52241', '-901', '-252471', '-266151',
       '-353326', '375782', '20219', '9294673', '4448583', '4947589',
       '4128078', '4356800', '-5.93', '25.99', '10.39', '7.43', nan,
       '0.48', '36.34', '557.85', '1.03', '262.42', '0.08', '0.04', nan,
       '0.08', '9.1'], dtype=object)

In [5]:
df['2019-09-30'].values.T.astype('float32')

array([-2.870000e+00,  8.290000e+00, -2.860000e+00, -5.460000e+00,
       -5.580000e+00,  8.821000e+01, -5.910000e+00, -6.110000e+00,
       -5.552000e+01, -6.130000e+00, -2.870000e+00,           nan,
        1.069000e+01,  2.105000e+01, -1.480900e+02,  1.080000e+00,
        9.400000e-01,  2.546000e+01,  2.008530e+03,  5.323000e+01,
                 nan,  4.677000e+01,           nan,           nan,
        1.138100e+02,           nan,           nan,           nan,
        1.114800e+02,  9.496000e+01,           nan,           nan,
       -9.500000e+00, -3.277100e+02, -7.040000e+00, -1.790000e+00,
       -5.500000e-01,           nan,           nan,  4.511542e+06,
        3.738880e+05, -2.515700e+05, -5.224100e+04, -9.010000e+02,
       -2.524710e+05, -2.661510e+05, -3.533260e+05,  3.757820e+05,
        2.021900e+04,  9.294673e+06,  4.448583e+06,  4.947589e+06,
        4.128078e+06,  4.356800e+06, -5.930000e+00,  2.599000e+01,
        1.039000e+01,  7.430000e+00,           nan,  4.800000e-01,
        3.634000e+01,  5.578500e+02,  1.030000e+00,  2.624200e+02,
        8.000000e-02,  4.000000e-02,           nan,  8.000000e-02,
        9.100000e+00], dtype=float32)

In [7]:
df = pd.DataFrame(total_list,columns=df_names)
df['code'] = code_list

In [8]:
df

报告日期,总资产利润率(%),主营业务利润率(%),总资产净利润率(%),成本费用利润率(%),营业利润率(%),主营业务成本率(%),销售净利率(%),净资产收益率(%),股本报酬率(%),净资产报酬率(%),...,存货周转天数(天),总资产周转天数(天),流动资产周转率(次),流动资产周转天数(天),经营现金净流量对销售收入比率(%),资产的经营现金流量回报率(%),经营现金净流量与净利润的比率(%),经营现金净流量对负债比率(%),现金流量比率(%),code
0,1.05,16.02,1.1,2.85,2.73,83.38,2.29,4.28,12.64,4.3,...,159.13,559.82,0.99,273.2,0.01,0.01,0.53,0.01,0.91,002863
1,0.72,20.79,0.72,3,2.76,78.59,1.59,1.47,5.18,1.33,...,102.39,600.53,0.75,358.99,0.04,0.02,2.49,0.04,4.55,002590
2,1.02,18.12,1.03,4.99,4.62,80.99,4.24,1.31,9.29,1.31,...,156.59,1115.24,0.51,525.19,0.15,0.04,3.61,0.17,17.08,300733
3,2.74,28.9,3.2,10.37,9.15,70.03,8.36,4.58,9.95,4.64,...,79.21,706.25,0.71,378.31,0.19,0.06,2.25,0.15,35.12,300643
4,1.82,24.19,2.09,6.52,5.66,74.75,5.21,3.43,17.59,3.39,...,111.08,672.81,0.78,346.2,0.08,0.03,1.54,0.06,7.57,603286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,5.11,5.56,4.98,14.17,13.79,92.18,15.04,7.97,62.71,7.83,...,43.05,815.22,0.75,358.99,-0.21,-0.07,-1.42,-0.21,-29.63,601238
132,0.21,17.01,0.2,0.49,0.26,81.59,0.46,0.3,0.9,0.3,...,106.43,615.74,0.93,291.86,0.11,0.05,23.51,0.16,17.4,002708
133,3.31,21.49,3.75,15.54,14.91,77.17,15.58,7.91,70.62,7.49,...,91.38,1120.8,0.84,321.47,0.27,0.06,1.74,0.1,11.93,603035
134,3.3,29.62,3.32,19.67,16.5,69.6,14.37,6.23,53.81,6.23,...,160.63,1169.34,0.28,950.37,0.19,0.04,1.33,0.09,9.35,300652
135,-2.87,8.29,-2.86,-5.46,-5.58,88.21,-5.91,-6.11,-55.52,-6.13,...,36.34,557.85,1.03,262.42,0.08,0.04,NaN,0.08,9.1,000625

In [9]:
df.to_csv('car.csv')